### ISSUE TITLE
Pass a Result object

### ISSUE THREAD

**Issue by ai** [postcss/postcss-plugin-context#2]
Plugin function accepts two arguments: `css` and `result`.

Without proxing last `result` plugins will not be able to return warnings.

But you need one hack: `result.css` should be a same as `css`. Also plugin may create totally new `Root` on `result.css`.

**Comment by ben-eb** [comment]
Would this be a matter of simply updating this argument to have `result` as well? https://github.com/postcss/postcss-plugin-context/blob/master/index.js#L23

The root situation is I think fine, because it is all scoped inside a context. But it would be good to include integration tests for plugins that do this.
